[package]
name = "ruckus_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
tauri = "1.6.5"
thiserror = "1.0.60"
ruckus_rack = { path = "../ruckus_rack" }
