name: Back End CI

on:
    push:
        branches: [main]
        paths:
          - 'src/**'
          - 'Cargo.toml'
          - 'Cargo.lock'
    pull_request:
        branches: [main]
        paths:
          - 'src/**'
          - 'Cargo.toml'
          - 'Cargo.lock'

env:
    CARGO_TERM_COLOR: always
    RUSTFLAGS: '-Dwarnings'

jobs:
    # Run cargo test
    test:
        name: Test Suite
        runs-on: ubuntu-latest
        timeout-minutes: 30
        container:
            image: shakesbeare/rust-ci-container
            # volumes: 
            #   ~/.cargo/bin/
            #   ~/.cargo/registry/index/
            #   ~/.cargo/registry/cache/
            #   ~/.cargo/git/db/
            #   target/
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}
            - name: Install nightly toolchain
              uses: dtolnay/rust-toolchain@nightly
            - name: Install cargo-nextest
              run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
            - name: Install Dependencies
              run: sudo apt-get update; sudo apt-get install --no-install-recommends libgtk-3-dev libsoup2.4 javascriptcoregtk-4.0 webkit2gtk-4.0 libasound2-dev
            - name: Run Tests
              run: cargo-nextest nextest run && cargo t --doc

    # Run cargo clippy -- -D warnings
    clippy_check:
        name: Clippy
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.toml') }}
            - name: Install nightly toolchain
              uses: dtolnay/rust-toolchain@nightly
              with:
                  components: clippy
            - name: Install Dependencies
              run: sudo apt-get update; sudo apt-get install --no-install-recommends libgtk-3-dev libsoup2.4 javascriptcoregtk-4.0 webkit2gtk-4.0 libasound2-dev
            - name: Run clippy
              run: cargo clippy -- -D warnings

    # Run cargo fmt --all -- --check
    format:
        name: Check Formatting
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Install nightly toolchain
              uses: dtolnay/rust-toolchain@nightly
              with:
                  components: rustfmt
            - name: Run cargo fmt
              run: cargo fmt --all -- --check
