name: Back End CI

on:
    push:
        branches: [main]
        paths:
            - 'src/**'
            - 'Cargo.toml'
            - 'Cargo.lock'
    pull_request:
        branches: [main]
        paths:
            - 'src/**'
            - 'Cargo.toml'
            - 'Cargo.lock'

env:
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
    RUSTFLAGS: '-Dwarnings'

jobs:
    # Run cargo test
    test:
        name: Test Suite
        runs-on: ubuntu-latest
        timeout-minutes: 30
        container:
            image: shakesbeare/rust-ci-container
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Cache
              uses: Swatinem/rust-cache@v2
              with:
                  key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}
            - name: Install cargo-nextest
              run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
            - name: Run Tests
              run: cargo-nextest nextest run && cargo t --doc

    # Run cargo clippy -- -D warnings
    clippy_check:
        name: Clippy
        runs-on: ubuntu-latest
        timeout-minutes: 30
        container:
            image: shakesbeare/rust-ci-container
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Cache
              uses: Swatinem/rust-cache@v2
              with:
                  key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}
            - name: Run clippy
              run: cargo clippy -- -D warnings

    # Run cargo fmt --all -- --check
    format:
        name: Check Formatting
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Run cargo fmt
              run: cargo fmt --all -- --check
