name: TS CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        name: Test Suite
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: v20.4

            - name: Install all dependencies
              run: |
                  npm i

            - name: Run tests
              run: sh ./scripts/fmt-lint-check.sh
