name: TS CI

on:
    push:
        branches: [2024-5-8-TK-TSUnitTesting]
    pull_request:
        branches: [2024-5-8-TK-TSUnitTesting]

jobs:
    test:
        name: Test Suite
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: v20.4

            - name: View stuff
              run: |
                ls -la
                cd ../
                ls -la

            - name: Install all dependencies
              run: |
                npm i

            - name: Run tests
              run: sh ./scripts/fmt-lint-check.sh
